name: React Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  IMAGE_NAME: brunomarch/build-react
  NODE_VERSION: "24.14.0"

jobs:
  build:
    name: Build e Test
    runs-on: [self-hosted, Linux, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

  docker:
    name: Docker Build & Push
    runs-on: [self-hosted, Linux, build]
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Definir se deve fazer push
        id: docker-config
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "PUSH_IMAGE=true" >> $GITHUB_ENV
          else
            echo "PUSH_IMAGE=false" >> $GITHUB_ENV
          fi

      - name: Build (e Push condicional) da imagem
        uses: ./.github/actions/docker-build-push
        with:
          image-name: "${{ env.IMAGE_NAME }}"
          image-tag: "${{ github.sha }}"
          push: "${{ steps.docker-config.outputs.PUSH_IMAGE }}"
          docker-username: "${{ secrets.DOCKER_USERNAME }}"
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
