name: React Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  IMAGE_NAME: brunomarch/build-react
  NODE_VERSION: '24.14.0'

jobs:
  build:
    name: Build e Test
    runs-on: [self-hosted, Linux, build]
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24.14.0'
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Build
      run: npm run build

  docker-build:
    name: Build Docker Image
    runs-on: [self-hosted, Linux, build]
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build da imagem (sem push)
        uses: ./.github/actions/docker-build-push
        with:
          image-name: ${{ env.IMAGE_NAME }}
          image-tag: ${{ github.sha }}
          push: "false"

  docker-push:
    name: Docker Push
    runs-on: [self-hosted, Linux, build]
    needs: docker-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build e Push da imagem
        uses: ./.github/actions/docker-build-push
        with:
          image-name: ${{ env.IMAGE_NAME }}
          image-tag: ${{ github.sha }}
          push: "true"
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}